const entries = [
  ['ARI', 'Arizona', 'Cardinals'],
  ['ATL', 'Atlanta', 'Falcons'],
  ['BAL', 'Baltimore', 'Ravens'],
  ['BUF', 'Buffalo', 'Bills'],
  ['CAR', 'Carolina', 'Panthers'],
  ['CHI', 'Chicago', 'Bears'],
  ['CIN', 'Cincinnati', 'Bengals'],
  ['CLE', 'Cleveland', 'Browns'],
  ['DAL', 'Dallas', 'Cowboys'],
  ['DEN', 'Denver', 'Broncos'],
  ['DET', 'Detroit', 'Lions'],
  ['GB', 'Green Bay', 'Packers'],
  ['HOU', 'Houston', 'Texans'],
  ['IND', 'Indianapolis', 'Colts'],
  ['JAX', 'Jacksonville', 'Jaguars'],
  ['KC', 'Kansas City', 'Chiefs'],
  ['LV', 'Las Vegas', 'Raiders'],
  ['LAC', 'Los Angeles', 'Chargers'],
  ['LAR', 'Los Angeles', 'Rams'],
  ['MIA', 'Miami', 'Dolphins'],
  ['MIN', 'Minnesota', 'Vikings'],
  ['NE', 'New England', 'Patriots'],
  ['NO', 'New Orleans', 'Saints'],
  ['NYG', 'New York', 'Giants'],
  ['NYJ', 'New York', 'Jets'],
  ['PHI', 'Philadelphia', 'Eagles'],
  ['PIT', 'Pittsburgh', 'Steelers'],
  ['SF', 'San Francisco', '49ers'],
  ['SEA', 'Seattle', 'Seahawks'],
  ['TB', 'Tampa Bay', 'Buccaneers'],
  ['TEN', 'Tennessee', 'Titans'],
  ['WAS', 'Washington', 'Commanders'],
];
export const teams = entries.map(([abbreviation, city, nickname]) => ({
  abbreviation,
  city,
  nickname,
  fullName: `${city} ${nickname}`,
}));
const byName = new Map(teams.map((t) => [t.fullName, t]));
export const team = (name: string) =>
  byName.get(name) ?? {
    abbreviation: name,
    city: '',
    nickname: name,
    fullName: name,
  };
